name: Service Keep-Alive

on:
  schedule:
    # Runs every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch: # Allows manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Backend
        run: curl -s -o /dev/null -w "%{http_code}" https://cloudops-backend-cloudops-v1.onrender.com
      
      - name: Ping CloudOps Frontend
        run: curl -s -o /dev/null -w "%{http_code}" https://cloudops-frontend-cloudops-v1.onrender.com
      
      - name: Ping MNKHAN Services
        run: curl -s -o /dev/null -w "%{http_code}" https://mnkhan.onrender.com/api/services
